#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 28 15:38:16 2020

@author: crodri
"""

'''
Script to download news from Agència Calatana de Notícies (ACN) website
using Selenium IDE and Selenium Web Driver for Firefox.

https://addons.mozilla.org/en-US/firefox/addon/selenium-ide/
https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz

Usage: pytest test_acn.py

Author: https://github.com/aasensios
'''

# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from pathlib import Path
import os


class TestAcn():
    def setup_method(self, method):
        # Prevent download dialog
        # https://stackoverflow.com/a/62254004
        downloads_dir = os.path.join(Path().absolute(), 'downloaded_files')
        options = webdriver.FirefoxOptions()
        options.set_preference('browser.download.manager.showWhenStarting', False)
        options.set_preference('browser.download.dir', downloads_dir)
        options.set_preference('browser.download.folderList', 2)  # 0: Desktop, 1: Downloads, 2: custom directory
        options.set_preference('browser.helperApps.neverAsk.saveToDisk', 'text/html')  # Checked 'content-type: text/html' in Browser: F12 > Network > Headers
        self.driver = webdriver.Firefox(
            executable_path=os.path.join(Path().absolute(), 'geckodriver-v0.27.0-linux64/geckodriver'),
            options=options,
        )
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_login_and_download_text_file(self):
        self.driver.get("https://www.acn.cat/")

        # Login
        self.driver.find_element(By.LINK_TEXT, "Entra").click()
        self.driver.find_element(By.NAME, "username").send_keys("TEXT")
        self.driver.find_element(By.NAME, "password").send_keys("1865GB")
        self.driver.find_element(By.NAME, "Submit").click()
        alltitles = self.driver.find_elements_by_class_name('uk-title')
        for title in alltitles:
            print(title.text)
            t = title.text
            a = title.find_elements(By.TAG_NAME, 'a')[0]
            itemurl = a.get_attribute('href')
            # Load specific pages
            self.driver.get(itemurl)
            # Trigger the download button for the clean text file
            self.driver.find_element(By.CLASS_NAME, "uk-button").click()